# Generated by Django 5.2.4 on 2025-07-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0003_custommodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModel',
        ),
    ]
