# Generated by Django 5.2.4 on 2025-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0005_healthactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family_id',
            field=models.IntegerField(),
        ),
    ]
